### ISSUE TITLE
Self-hosted Directus & Nuxt Agency OS issue

### ISSUE THREAD

**Issue by samhallam16021** [directus-labs/agency-os#76]
Hello, I have set up directus and nuxt on a self hosted ubuntu server according to your readme instructions. It seemingly installs fine with some small warning on the template application. But when I run pnpm dev I get the following error

`[nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'id')
  at ./components/base/VGallery.vue:101:17
  at Module.ssrRenderList (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:442:7)
  at _sfc_ssrRender (./components/base/VGallery.vue:96:26)
  at renderComponentSubTree (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:695:9)
  at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12)
  at Module.ssrRenderComponent (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
  at ./components/blocks/Gallery.vue:75:40
  at renderFnWithContext (./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:815:13)
  at ssrRenderSlotInner (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:111:17)
  at Module.ssrRenderSlot (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:93:3)
definePageMeta() is a compiler-hint helper that is only usable inside the script block of a single file component which is also a page. Its arguments should be compiled away and passing it at runtime has no effect.`

Has this error been seen before?

**Comment by bryantgillespie** [comment]
Make sure you have CORS properly configured on your Directus instance.
See #73

**Comment by samhallam16021** [comment]
Hi Bryant, thanks for getting back to me.

I have this currently in the directus docker file which I thought would be enough.
      CORS_ENABLED: true
      CORS_METHODS: OPTIONS,GET,POST,PATCH,DELETE
      CORS_ORIGIN: "array:https://redacted-url1.com,https://redacted-url2.com"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization,X-Requested-With"
      CORS_EXPOSED_HEADERS: "Content-Range,X-Content-Range,Content-Range"

**Comment by samhallam16021** [comment]
I am also seeing this error in the pnpm dev but I am sure they are unrelated?  ERROR  This module cannot be imported in server runtime. [importing @nuxt/kit from node_modules/.pnpm/nuxt-simple-sitemap@3.4.0_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.21_jwt-decode@3.1.2_nux_undt3zhfvsokhebtqgy6i27fba/node_modules/nuxt-simple-sitemap/dist/runtime/util/pageUtils.mjs]

**Comment by amo42** [comment]
> I am also seeing this error in the pnpm dev but I am sure they are unrelated? ERROR This module cannot be imported in server runtime. [importing @nuxt/kit from node_modules/.pnpm/nuxt-simple-sitemap@[3.4.0_@nuxt](mailto:3.4.0_@nuxt)+devtools@[1.0.8_@vue](mailto:1.0.8_@vue)+compiler-core@[3.4.21_jwt-decode@3.1.2_nux_undt3zhfvsokhebtqgy6i27fba](mailto:3.4.21_jwt-decode@3.1.2_nux_undt3zhfvsokhebtqgy6i27fba)/node_modules/nuxt-simple-sitemap/dist/runtime/util/pageUtils.mjs]

Hi @samhallam16021 may I ask you how you solved your issue? I feel like I run into the same issue, but already checked the CORS settings
