### ISSUE TITLE
Error updating block_gallery_files

### ISSUE THREAD

**Issue by salohcin714** [directus-labs/agency-os#92]
When applying the Agency OS template, I am receiving the following error:

```
Error updating block_gallery_files [
  {
    message: 'Invalid foreign key for field "directus_files_id" in collection "block_gallery_files".',
    extensions: {
      code: 'INVALID_FOREIGN_KEY',
      collection: 'block_gallery_files',
      field: 'directus_files_id'
    }
  }
]
```

The CLI then finishes, but when I try to then load the Nuxt site's homepage, I get the following

```
 {
  "url": "/",
  "statusCode": 500,
  "statusMessage": "",
  "message": "Cannot read properties of null (reading 'id')",
  "stack": "<pre><span class=\"stack\">at ./components/base/VGallery.vue:101:17</span>\n<span class=\"stack internal\">at Module.ssrRenderList (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:433:7)</span>\n<span class=\"stack\">at _sfc_ssrRender (./components/base/VGallery.vue:96:26)</span>\n<span class=\"stack internal\">at renderComponentSubTree (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:683:9)</span>\n<span class=\"stack internal\">at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:631:12)</span>\n<span class=\"stack internal\">at Module.ssrRenderComponent (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)</span>\n<span class=\"stack\">at ./components/blocks/Gallery.vue:75:40</span>\n<span class=\"stack internal\">at renderFnWithContext (./node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:762:13)</span>\n<span class=\"stack internal\">at ssrRenderSlotInner (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:113:17)</span>\n<span class=\"stack internal\">at Module.ssrRenderSlot (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:95:3)</span></pre>"
}
```

**Comment by bryantgillespie** [comment]
This is most likely a permissions or CORS issue.
